// src/lib/roadmaps.js
// Career roadmap data for all 8 fields

export const roadmaps = [
  {
    slug: 'ai-ml',
    name: 'AI / ML Engineering',
    icon: '🤖',
    color: '#7C3AED',
    tagline: 'Build the models powering tomorrow\'s products',
    avgSalaryFresher: '8-15 LPA',
    avgSalaryMid: '18-35 LPA',
    timeToJobReady: '6-9 months',
    demand: 'Very High',
    demandGrowth: '+45% YoY',
    openRolesIndia: '8,200+',
    overview: 'AI/ML engineers design, train, and deploy machine learning models — from classic ML to today\'s generative AI and LLMs. This is the highest-growth, highest-paying field for freshers right now in India.',
    stages: [
      {
        title: 'Foundations',
        duration: '0-2 months',
        skills: ['Python', 'NumPy & Pandas', 'Linear Algebra', 'Probability & Statistics', 'SQL'],
        milestone: 'Build 3 small data analysis projects using real datasets (Kaggle)',
        resources: ['CS50 Python (Harvard, free)', 'Khan Academy Linear Algebra', 'Kaggle Learn micro-courses'],
      },
      {
        title: 'Core Machine Learning',
        duration: '2-4 months',
        skills: ['Scikit-learn', 'Regression & Classification', 'Decision Trees & Ensembles', 'Model Evaluation', 'Feature Engineering'],
        milestone: 'Build an end-to-end ML pipeline: data cleaning → model → evaluation → deployment',
        resources: ['Andrew Ng Machine Learning Specialization (Coursera)', 'Hands-On ML with Scikit-Learn (book)'],
      },
      {
        title: 'Deep Learning & GenAI',
        duration: '4-7 months',
        skills: ['PyTorch / TensorFlow', 'Neural Networks', 'Transformers', 'LLMs & Prompt Engineering', 'RAG & Vector DBs', 'Fine-tuning'],
        milestone: 'Build a GenAI project — RAG chatbot or fine-tuned model — and deploy it publicly',
        resources: ['Fast.ai Practical Deep Learning', 'Hugging Face NLP Course', 'DeepLearning.AI GenAI courses'],
      },
      {
        title: 'Production & Interview Ready',
        duration: '7-9 months',
        skills: ['MLOps basics (Docker, APIs)', 'Model serving (FastAPI)', 'Cloud (AWS SageMaker / GCP Vertex)', 'System design for ML'],
        milestone: 'Have 2-3 polished portfolio projects on GitHub + can explain trade-offs in interviews',
        resources: ['MLOps Zoomcamp (free)', 'Designing ML Systems (book)'],
      },
    ],
    topCompaniesHiring: ['Zepto', 'Meesho', 'Razorpay', 'Google', 'Microsoft'],
    keyProjects: ['Resume parser using LLMs', 'Recommendation engine', 'Image classifier deployed as API', 'RAG-based Q&A bot'],
  },
  {
    slug: 'software-engineering',
    name: 'Software Engineering',
    icon: '💻',
    color: '#2563EB',
    tagline: 'The most in-demand, most stable tech career',
    avgSalaryFresher: '4-8 LPA',
    avgSalaryMid: '12-22 LPA',
    timeToJobReady: '4-6 months',
    demand: 'High',
    demandGrowth: '+18% YoY',
    openRolesIndia: '12,400+',
    overview: 'Software engineers build the products people use every day — web apps, backend systems, mobile apps. It\'s the largest job category for freshers in India with the most predictable hiring pipeline (campus drives, off-campus, referrals).',
    stages: [
      {
        title: 'Programming Fundamentals',
        duration: '0-1.5 months',
        skills: ['One language deeply (Python/Java/JS)', 'Data Structures', 'Algorithms basics', 'Git & GitHub'],
        milestone: 'Solve 50+ DSA problems on LeetCode/GFG, comfortable with arrays/strings/hashmaps',
        resources: ['Striver\'s DSA Sheet (free)', 'CS50 (Harvard)', 'freeCodeCamp'],
      },
      {
        title: 'Web Development',
        duration: '1.5-3 months',
        skills: ['HTML/CSS/JS', 'React or similar framework', 'REST APIs', 'Node.js or backend language', 'Databases (SQL + one NoSQL)'],
        milestone: 'Build and deploy 2 full-stack projects (e.g. e-commerce clone, blog platform)',
        resources: ['The Odin Project (free)', 'Full Stack Open (University of Helsinki, free)'],
      },
      {
        title: 'DSA Mastery',
        duration: '3-5 months',
        skills: ['Trees & Graphs', 'Dynamic Programming', 'System Design basics', 'Time/Space Complexity'],
        milestone: 'Solve 200+ problems, can do a medium LeetCode problem in 25-30 min',
        resources: ['Striver\'s A2Z DSA Course', 'NeetCode 150'],
      },
      {
        title: 'Interview & Placement Ready',
        duration: '5-6 months',
        skills: ['Mock interviews', 'Resume + GitHub polish', 'Behavioral interview prep', 'Company-specific prep'],
        milestone: 'Mock interview score 7+/10, apply to 20+ companies weekly',
        resources: ['Pramp (free mock interviews)', 'InterviewBit'],
      },
    ],
    topCompaniesHiring: ['Razorpay', 'Zepto', 'CRED', 'Swiggy', 'Lenskart'],
    keyProjects: ['Full-stack e-commerce app', 'Real-time chat app', 'URL shortener with analytics', 'Open source contribution'],
  },
  {
    slug: 'data',
    name: 'Data Science & Analytics',
    icon: '📊',
    color: '#0891B2',
    tagline: 'Turn raw data into business decisions',
    avgSalaryFresher: '3.5-7 LPA',
    avgSalaryMid: '8-16 LPA',
    timeToJobReady: '4-6 months',
    demand: 'High',
    demandGrowth: '+28% YoY',
    openRolesIndia: '6,800+',
    overview: 'Data analysts and scientists help companies make decisions using data — dashboards, A/B tests, predictive models. Great entry point into tech for non-CS backgrounds too, with strong demand across fintech, e-commerce, and startups.',
    stages: [
      {
        title: 'Data Fundamentals',
        duration: '0-1.5 months',
        skills: ['Excel/Google Sheets advanced', 'SQL (joins, window functions)', 'Statistics basics', 'Python or R basics'],
        milestone: 'Write complex SQL queries confidently, complete 5+ SQL challenges',
        resources: ['Mode SQL Tutorial (free)', 'StrataScratch'],
      },
      {
        title: 'Analysis & Visualization',
        duration: '1.5-3 months',
        skills: ['Pandas', 'Tableau or Power BI', 'Data cleaning', 'A/B testing concepts'],
        milestone: 'Build 3 dashboards analyzing real datasets, publish on portfolio site',
        resources: ['Kaggle datasets + competitions', 'Power BI free learning path'],
      },
      {
        title: 'Applied Machine Learning',
        duration: '3-5 months',
        skills: ['Scikit-learn', 'Regression/Classification', 'Feature engineering', 'Model interpretation'],
        milestone: 'Complete 1 end-to-end predictive modeling project with business framing',
        resources: ['Andrew Ng ML course', 'Kaggle Learn'],
      },
      {
        title: 'Business & Interview Ready',
        duration: '5-6 months',
        skills: ['Case study frameworks', 'Storytelling with data', 'SQL interview prep', 'Take-home assignment practice'],
        milestone: 'Can confidently solve a live SQL/case interview in 30 min',
        resources: ['DataLemur SQL interview prep'],
      },
    ],
    topCompaniesHiring: ['Groww', 'Meesho', 'PhysicsWallah', 'Ola Electric', 'Razorpay'],
    keyProjects: ['Sales dashboard with insights', 'Churn prediction model', 'A/B test analysis writeup', 'SQL portfolio on GitHub'],
  },
  {
    slug: 'cloud-devops',
    name: 'Cloud & DevOps',
    icon: '☁️',
    color: '#EA580C',
    tagline: 'Keep systems running at scale',
    avgSalaryFresher: '4-8 LPA',
    avgSalaryMid: '10-20 LPA',
    timeToJobReady: '5-7 months',
    demand: 'High',
    demandGrowth: '+22% YoY',
    openRolesIndia: '4,100+',
    overview: 'DevOps and Cloud engineers build the infrastructure that lets software ship fast and stay reliable. Fewer freshers target this directly, which means less competition once you have the fundamentals — most people transition in after 1-2 years as SWE.',
    stages: [
      {
        title: 'Linux & Networking',
        duration: '0-2 months',
        skills: ['Linux command line', 'Networking basics', 'Shell scripting', 'Git'],
        milestone: 'Comfortable navigating and scripting in a Linux terminal',
        resources: ['Linux Journey (free)', 'KodeKloud free courses'],
      },
      {
        title: 'Cloud Fundamentals',
        duration: '2-4 months',
        skills: ['AWS or GCP basics', 'EC2/Compute, S3/Storage, VPC', 'IAM & Security basics'],
        milestone: 'AWS Cloud Practitioner certification, deploy a basic app on cloud',
        resources: ['AWS Free Tier + AWS Skill Builder (free)'],
      },
      {
        title: 'Containers & CI/CD',
        duration: '4-6 months',
        skills: ['Docker', 'Kubernetes basics', 'CI/CD pipelines (GitHub Actions)', 'Infrastructure as Code (Terraform)'],
        milestone: 'Containerize an app, set up automated deployment pipeline',
        resources: ['KodeKloud Docker/K8s courses', 'TechWorld with Nana (YouTube)'],
      },
      {
        title: 'Production Ready',
        duration: '6-7 months',
        skills: ['Monitoring (Prometheus/Grafana)', 'Cost optimization', 'Incident response basics'],
        milestone: 'Build and document a full CI/CD pipeline project end to end',
        resources: ['AWS Solutions Architect Associate prep'],
      },
    ],
    topCompaniesHiring: ['Razorpay', 'Slice', 'Zepto', 'CRED', 'Groww'],
    keyProjects: ['Dockerized multi-service app', 'CI/CD pipeline with auto-deploy', 'Infra-as-code setup with Terraform'],
  },
  {
    slug: 'design',
    name: 'UI/UX Design',
    icon: '🎨',
    color: '#DB2777',
    tagline: 'Design products people love to use',
    avgSalaryFresher: '3.5-7 LPA',
    avgSalaryMid: '8-16 LPA',
    timeToJobReady: '4-6 months',
    demand: 'Medium',
    demandGrowth: '+12% YoY',
    openRolesIndia: '2,900+',
    overview: 'Product/UI/UX designers shape how digital products look, feel, and function. A strong portfolio matters more than a degree here — design is one of the most portfolio-driven hiring fields in tech.',
    stages: [
      {
        title: 'Design Fundamentals',
        duration: '0-1.5 months',
        skills: ['Design principles (color, typography, spacing)', 'Figma basics', 'User research basics'],
        milestone: 'Recreate 3 existing app screens pixel-perfect in Figma',
        resources: ['Figma official tutorials (free)', 'Laws of UX (free site)'],
      },
      {
        title: 'UX Process',
        duration: '1.5-3 months',
        skills: ['User personas & journeys', 'Wireframing', 'Usability testing basics', 'Information architecture'],
        milestone: 'Complete one full case study: research → wireframe → high-fidelity design',
        resources: ['Google UX Design Certificate (Coursera)'],
      },
      {
        title: 'Visual & Interaction Design',
        duration: '3-4.5 months',
        skills: ['Design systems', 'Micro-interactions / prototyping', 'Accessibility basics', 'Mobile + web design patterns'],
        milestone: 'Build a mini design system with reusable components',
        resources: ['Refactoring UI (book)', 'Material Design / Apple HIG docs'],
      },
      {
        title: 'Portfolio & Interview Ready',
        duration: '4.5-6 months',
        skills: ['Case study storytelling', 'Portfolio website', 'Design critique skills'],
        milestone: '3-4 polished case studies on a personal portfolio site',
        resources: ['Bestfolios.com (inspiration)'],
      },
    ],
    topCompaniesHiring: ['Razorpay', 'CRED', 'Groww', 'Lenskart', 'Meesho'],
    keyProjects: ['App redesign case study', 'Design system for a fictional product', 'Mobile app prototype with user testing'],
  },
  {
    slug: 'product',
    name: 'Product Management',
    icon: '📦',
    color: '#16A34A',
    tagline: 'Decide what gets built and why',
    avgSalaryFresher: '6-12 LPA',
    avgSalaryMid: '15-28 LPA',
    timeToJobReady: '6-8 months',
    demand: 'Medium',
    demandGrowth: '+20% YoY',
    openRolesIndia: '1,800+',
    overview: 'PMs sit between business, design, and engineering to decide what gets built. Hardest field to break into as a pure fresher — most successful entries come via APM programs or a strong technical/analytical background plus side projects.',
    stages: [
      {
        title: 'PM Fundamentals',
        duration: '0-2 months',
        skills: ['Product sense basics', 'SQL fundamentals', 'Market & competitor research', 'Basic metrics (DAU, retention, funnel)'],
        milestone: 'Write 3 product teardowns analyzing existing apps',
        resources: ['Reforge blog (free articles)', 'Lenny\'s Newsletter (free tier)'],
      },
      {
        title: 'Frameworks & Analytics',
        duration: '2-4 months',
        skills: ['Prioritization frameworks (RICE, MoSCoW)', 'A/B testing', 'Basic Figma for wireframes', 'Writing PRDs'],
        milestone: 'Write one full PRD for a feature idea, end to end',
        resources: ['Google Project Management Certificate'],
      },
      {
        title: 'Execution Experience',
        duration: '4-6 months',
        skills: ['Stakeholder communication', 'Roadmapping', 'User interviews', 'Data-informed decision making'],
        milestone: 'Lead a real or simulated product project (hackathon, college club, freelance)',
        resources: ['APM program prep guides'],
      },
      {
        title: 'Interview Ready',
        duration: '6-8 months',
        skills: ['Product sense interviews', 'Case interviews', 'Metrics interviews', 'Portfolio of teardowns'],
        milestone: 'Confidently answer "design a product for X" in 20 minutes',
        resources: ['Exponent.com practice questions'],
      },
    ],
    topCompaniesHiring: ['Razorpay', 'Zepto', 'Groww', 'CRED', 'Meesho'],
    keyProjects: ['Product teardown series (blog/LinkedIn)', 'A full PRD with mockups', 'Side project shipped end-to-end'],
  },
  {
    slug: 'marketing',
    name: 'Marketing & Growth',
    icon: '📣',
    color: '#CA8A04',
    tagline: 'Get products in front of the right people',
    avgSalaryFresher: '3-6 LPA',
    avgSalaryMid: '7-14 LPA',
    timeToJobReady: '3-5 months',
    demand: 'Medium',
    demandGrowth: '+15% YoY',
    openRolesIndia: '3,800+',
    overview: 'Growth and digital marketing roles are one of the fastest, lowest-barrier entries into tech companies — strong for freshers who can show real campaigns, even small ones, rather than just certificates.',
    stages: [
      {
        title: 'Marketing Fundamentals',
        duration: '0-1.5 months',
        skills: ['SEO basics', 'Content writing', 'Social media strategy', 'Basic analytics (GA4)'],
        milestone: 'Run and document one small organic growth experiment',
        resources: ['Google Digital Garage (free)', 'HubSpot Academy (free)'],
      },
      {
        title: 'Performance Marketing',
        duration: '1.5-3 months',
        skills: ['Google Ads basics', 'Meta Ads basics', 'Funnel metrics (CAC, CTR, conversion)', 'A/B testing ad creatives'],
        milestone: 'Run a small ad campaign (even ₹500 budget) and report on results',
        resources: ['Google Ads / Meta Blueprint certifications (free)'],
      },
      {
        title: 'Growth & Analytics',
        duration: '3-4.5 months',
        skills: ['SQL basics for marketers', 'Cohort analysis', 'Email/WhatsApp marketing', 'Growth loops thinking'],
        milestone: 'Build a growth case study analyzing a real or fictional product\'s funnel',
        resources: ['Reforge growth content (free articles)'],
      },
      {
        title: 'Portfolio & Interview Ready',
        duration: '4.5-5 months',
        skills: ['Campaign portfolio', 'Storytelling with numbers', 'Tool proficiency (GA4, Meta Ads Manager)'],
        milestone: '2-3 documented campaigns with clear before/after metrics',
        resources: ['GrowthHackers.com case studies'],
      },
    ],
    topCompaniesHiring: ['Meesho', 'PhysicsWallah', 'Lenskart', 'Slice', 'Ola Electric'],
    keyProjects: ['Organic growth case study', 'Paid ad campaign report', 'Content calendar + execution for a brand'],
  },
  {
    slug: 'finance',
    name: 'Finance & Operations',
    icon: '💰',
    color: '#0D9488',
    tagline: 'Power the numbers behind every business',
    avgSalaryFresher: '3.5-7 LPA',
    avgSalaryMid: '8-16 LPA',
    timeToJobReady: '3-5 months',
    demand: 'Medium',
    demandGrowth: '+14% YoY',
    openRolesIndia: '5,600+',
    overview: 'Finance and operations roles in fintech and startups (risk, credit, business analytics) are growing fast and value Excel + analytical thinking over a finance degree alone — strong path for commerce and engineering freshers alike.',
    stages: [
      {
        title: 'Foundations',
        duration: '0-1.5 months',
        skills: ['Advanced Excel', 'Basic accounting concepts', 'Financial statements reading'],
        milestone: 'Build a financial model in Excel for a sample company',
        resources: ['Corporate Finance Institute free courses'],
      },
      {
        title: 'Analytics Tools',
        duration: '1.5-3 months',
        skills: ['SQL basics', 'Power BI / Tableau', 'Basic statistics', 'Risk concepts (for fintech roles)'],
        milestone: 'Build a dashboard analyzing financial/operational data',
        resources: ['Mode SQL tutorial', 'Power BI learning path'],
      },
      {
        title: 'Domain Specialization',
        duration: '3-4.5 months',
        skills: ['Pick a track: Credit/Risk, FP&A, or Ops Analytics', 'Industry-specific KPIs', 'Process improvement basics'],
        milestone: 'Complete one domain-specific case study or certification',
        resources: ['NSE Academy certifications (India-specific)'],
      },
      {
        title: 'Interview Ready',
        duration: '4.5-5 months',
        skills: ['Case interview practice', 'Excel test prep', 'Industry awareness (read fintech news)'],
        milestone: 'Comfortable doing a live Excel/SQL case test in 30 min',
        resources: ['WallStreetPrep free resources'],
      },
    ],
    topCompaniesHiring: ['Razorpay', 'Groww', 'Slice', 'CRED', 'Zepto'],
    keyProjects: ['Financial model in Excel', 'Risk/credit scoring case study', 'Operations dashboard with KPIs'],
  },
]

export function getRoadmapBySlug(slug) {
  return roadmaps.find(r => r.slug === slug)
}
