// src/lib/startups.js
// Funded Indian startups data — all info from public sources

export const startups = [
  {
    id: 1,
    name: 'Zepto',
    domain: 'zeptonow.com',
    stage: 'Series F',
    location: 'Mumbai, India',
    funding: '$1.4B',
    teamSize: '3,000+',
    rating: '4.1',
    description: '10-minute grocery delivery startup disrupting quick commerce in India. One of the fastest-growing consumer tech companies.',
    hiringFor: ['Software Engineer', 'Data Analyst', 'Product Manager', 'ML Engineer', 'DevOps'],
    freshersHired: '200+ freshers/year',
    avgSalary: '8-18 LPA',
    skills: ['Python', 'React', 'Node.js', 'SQL', 'AWS'],
    careersUrl: 'https://www.zeptonow.com/careers',
    perks: ['ESOP', 'Health Insurance', 'Free Groceries', 'Flexible Hours'],
  },
  {
    id: 2,
    name: 'Razorpay',
    domain: 'razorpay.com',
    stage: 'Series F',
    location: 'Bangalore, India',
    funding: '$741M',
    teamSize: '3,500+',
    rating: '4.3',
    description: 'India\'s leading payment gateway powering 8M+ businesses. Builds APIs, banking products, and fintech infrastructure.',
    hiringFor: ['Backend Engineer', 'Frontend Engineer', 'Data Scientist', 'Risk Analyst', 'SDE-1'],
    freshersHired: '150+ freshers/year',
    avgSalary: '12-22 LPA',
    skills: ['Java', 'Go', 'React', 'Kafka', 'MySQL'],
    careersUrl: 'https://razorpay.com/jobs',
    perks: ['ESOP', 'Health Insurance', 'Learning Budget', 'Hybrid Work'],
  },
  {
    id: 3,
    name: 'CRED',
    domain: 'cred.club',
    stage: 'Series F',
    location: 'Bangalore, India',
    funding: '$800M',
    teamSize: '1,500+',
    rating: '4.2',
    description: 'Premium fintech platform for creditworthy Indians. Offers credit card payments, loans, and exclusive member rewards.',
    hiringFor: ['iOS Developer', 'Android Developer', 'Data Engineer', 'Product Designer', 'SDE'],
    freshersHired: '100+ freshers/year',
    avgSalary: '15-28 LPA',
    skills: ['Swift', 'Kotlin', 'Python', 'Spark', 'Figma'],
    careersUrl: 'https://cred.club/careers',
    perks: ['High Salary', 'ESOP', 'Premium Office', 'Health Insurance'],
  },
  {
    id: 4,
    name: 'Groww',
    domain: 'groww.in',
    stage: 'Series E',
    location: 'Bangalore, India',
    funding: '$733M',
    teamSize: '3,000+',
    rating: '4.2',
    description: 'India\'s largest retail investment platform with 50M+ users investing in stocks, mutual funds, and crypto.',
    hiringFor: ['Software Engineer', 'Data Scientist', 'Business Analyst', 'Risk Analyst', 'ML Engineer'],
    freshersHired: '200+ freshers/year',
    avgSalary: '10-20 LPA',
    skills: ['Python', 'Java', 'SQL', 'Spark', 'React'],
    careersUrl: 'https://groww.in/open-positions',
    perks: ['ESOP', 'Health Insurance', 'Learning Allowance', 'Hybrid Work'],
  },
  {
    id: 5,
    name: 'PhysicsWallah',
    domain: 'pw.live',
    stage: 'Series B',
    location: 'Noida, India',
    funding: '$210M',
    teamSize: '10,000+',
    rating: '3.9',
    description: 'India\'s most affordable edtech platform with 10M+ students. Makes quality education accessible for JEE, NEET, and UPSC.',
    hiringFor: ['Content Developer', 'Software Engineer', 'Growth Manager', 'Data Analyst', 'Video Editor'],
    freshersHired: '500+ freshers/year',
    avgSalary: '4-10 LPA',
    skills: ['Python', 'React', 'Marketing', 'Content Writing', 'SQL'],
    careersUrl: 'https://apply.workable.com/pw-skills',
    perks: ['High Volume Hiring', 'Learning Access', 'Health Insurance', 'Remote Options'],
  },
  {
    id: 6,
    name: 'Meesho',
    domain: 'meesho.com',
    stage: 'Series F',
    location: 'Bangalore, India',
    funding: '$1.1B',
    teamSize: '4,000+',
    rating: '4.0',
    description: 'Social commerce platform empowering 15M+ small businesses across India, especially in Tier 2 and 3 cities.',
    hiringFor: ['Software Engineer', 'Data Scientist', 'Product Manager', 'ML Engineer', 'Supply Chain Analyst'],
    freshersHired: '300+ freshers/year',
    avgSalary: '10-22 LPA',
    skills: ['Python', 'Java', 'Go', 'SQL', 'Kubernetes'],
    careersUrl: 'https://meesho.io/careers',
    perks: ['ESOP', 'Health Insurance', 'Relocation Bonus', 'Hybrid Work'],
  },
  {
    id: 7,
    name: 'Ola Electric',
    domain: 'olaelectric.com',
    stage: 'Series D+',
    location: 'Bangalore, India',
    funding: '$938M',
    teamSize: '5,000+',
    rating: '3.8',
    description: 'India\'s #1 EV manufacturer building scooters, bikes, and cells. Mission to make EVs affordable for every Indian.',
    hiringFor: ['Embedded Engineer', 'Battery Engineer', 'Software Engineer', 'Data Analyst', 'Manufacturing Engineer'],
    freshersHired: '400+ freshers/year',
    avgSalary: '6-16 LPA',
    skills: ['C/C++', 'Python', 'CAD', 'MATLAB', 'SQL'],
    careersUrl: 'https://olaelectric.com/careers',
    perks: ['EV Subsidy', 'Health Insurance', 'ESOP', 'Canteen'],
  },
  {
    id: 8,
    name: 'Lenskart',
    domain: 'lenskart.com',
    stage: 'Series H',
    location: 'Faridabad, India',
    funding: '$772M',
    teamSize: '5,000+',
    rating: '3.9',
    description: 'Omnichannel eyewear brand with 2,000+ stores and strong D2C presence. Using AI for virtual try-on and personalization.',
    hiringFor: ['UI/UX Designer', 'Product Manager', 'Data Analyst', 'Full Stack Engineer', 'Store Manager'],
    freshersHired: '200+ freshers/year',
    avgSalary: '5-14 LPA',
    skills: ['React', 'Python', 'Figma', 'SQL', 'Node.js'],
    careersUrl: 'https://lenskart.com/careers',
    perks: ['Free Eyewear', 'Health Insurance', 'Hybrid Work', 'Learning Budget'],
  },
  {
    id: 9,
    name: 'Slice',
    domain: 'sliceit.in',
    stage: 'Series B',
    location: 'Bangalore, India',
    funding: '$220M',
    teamSize: '1,000+',
    rating: '4.0',
    description: 'Next-gen banking super app for millennials. Offers UPI, credit line, and savings accounts with a focus on Gen Z users.',
    hiringFor: ['Backend Engineer', 'Risk Analyst', 'Data Scientist', 'Credit Analyst', 'DevOps Engineer'],
    freshersHired: '100+ freshers/year',
    avgSalary: '8-18 LPA',
    skills: ['Python', 'Java', 'SQL', 'AWS', 'Kafka'],
    careersUrl: 'https://sliceit.in/careers',
    perks: ['ESOP', 'Health Insurance', 'Flexible Hours', 'Learning Budget'],
  },
  {
    id: 10,
    name: 'Nykaa',
    domain: 'nykaa.com',
    stage: 'Series D+',
    location: 'Mumbai, India',
    funding: '$795M',
    teamSize: '3,500+',
    rating: '3.8',
    description: 'India\'s leading beauty & fashion ecommerce platform with 5,000+ brands. Strong in D2C and private label business.',
    hiringFor: ['Frontend Engineer', 'Data Analyst', 'Digital Marketing', 'Product Manager', 'Category Manager'],
    freshersHired: '150+ freshers/year',
    avgSalary: '5-12 LPA',
    skills: ['React', 'Python', 'SQL', 'Marketing', 'Excel'],
    careersUrl: 'https://careers.nykaa.com',
    perks: ['Product Discounts', 'Health Insurance', 'Hybrid Work', 'Learning Budget'],
  },
  {
    id: 11,
    name: 'BrowserStack',
    domain: 'browserstack.com',
    stage: 'Series B',
    location: 'Mumbai, India',
    funding: '$200M',
    teamSize: '1,500+',
    rating: '4.5',
    description: 'World\'s leading software testing platform used by Microsoft, Twitter, and Amazon. 100% bootstrapped till Series B.',
    hiringFor: ['Software Engineer', 'QA Engineer', 'DevOps', 'Customer Success', 'Sales Engineer'],
    freshersHired: '80+ freshers/year',
    avgSalary: '10-20 LPA',
    skills: ['Java', 'Python', 'Selenium', 'AWS', 'Docker'],
    careersUrl: 'https://www.browserstack.com/careers',
    perks: ['Best in class salary', 'Remote friendly', 'Health Insurance', 'Learning Budget'],
  },
  {
    id: 12,
    name: 'Darwinbox',
    domain: 'darwinbox.com',
    stage: 'Series D',
    location: 'Hyderabad, India',
    funding: '$140M',
    teamSize: '1,000+',
    rating: '4.2',
    description: 'Asia\'s fastest growing HR tech platform used by 850+ enterprises. Full-stack HRMS with AI-powered people analytics.',
    hiringFor: ['SDE-1', 'Frontend Engineer', 'Data Analyst', 'Implementation Consultant', 'Product Manager'],
    freshersHired: '100+ freshers/year',
    avgSalary: '7-16 LPA',
    skills: ['React', 'Node.js', 'Python', 'SQL', 'AWS'],
    careersUrl: 'https://darwinbox.com/careers',
    perks: ['ESOP', 'Health Insurance', 'Hybrid Work', 'Quarterly offsites'],
  },
]

export const domains = ['All', 'Fintech', 'Edtech', 'Ecommerce', 'Logistics', 'Healthtech', 'SaaS', 'Consumer']
export const stages = ['All', 'Series A', 'Series B', 'Series C', 'Series D+', 'Series E', 'Series F', 'Series H']
