'use client'
import { useState } from 'react'
import { AlertCircle, X, Info } from 'lucide-react'

// Reusable disclaimer component — different types for different pages
export default function Disclaimer({ type = 'general', dismissible = true }) {
  const [dismissed, setDismissed] = useState(false)
  if (dismissed) return null

  const disclaimers = {
    ai_jobs: {
      icon: Info,
      color: 'var(--amber)',
      bg: 'var(--amber-light)',
      title: 'AI-Generated Results — Not Real Job Listings',
      text: 'Jobs shown are AI suggestions based on your resume skills — not actual live postings. Match % scores are estimates, not guarantees. Always verify opportunities directly on company websites or LinkedIn before applying.',
    },
    ats_score: {
      icon: Info,
      color: '#0891B2',
      bg: '#ECFEFF',
      title: 'Score is an AI Estimate — Not a Guarantee',
      text: 'ATS scores are generated by AI and are approximate indicators only. Different companies use different ATS systems with different rules. This score is a guide to improve your resume — not a prediction of interview shortlisting.',
    },
    resume_tailor: {
      icon: AlertCircle,
      color: 'var(--amber)',
      bg: 'var(--amber-light)',
      title: 'AI Rewrites Existing Content — Always Verify',
      text: 'Resume Tailor only rephrases and restructures your existing experience — it never adds fake information. However, always review the output carefully before submitting to any employer. You are responsible for the accuracy of your resume.',
    },
    mentors: {
      icon: AlertCircle,
      color: 'var(--amber)',
      bg: 'var(--amber-light)',
      title: 'Demo Profiles — Real Sessions Coming Soon',
      text: 'Mentor profiles shown on this page are for demonstration purposes only. No real booking or payment is processed. Ratings and session counts are illustrative. Real verified mentor sessions will be available soon.',
    },
    startups: {
      icon: Info,
      color: '#0891B2',
      bg: '#ECFEFF',
      title: 'Company Data May Not Reflect Current Status',
      text: 'Startup information (funding, roles, headcount) is sourced from public data and may not be fully up to date. Always verify open roles directly on company career pages or LinkedIn. JobReady is not affiliated with any company listed.',
    },
    placements: {
      icon: Info,
      color: 'var(--blue)',
      bg: 'var(--blue-light)',
      title: 'Placement Stories Are Self-Reported',
      text: 'Stories on the Placement Wall are submitted by users and are not independently verified by JobReady. Individual results may vary. Getting placed depends on many factors beyond using any single tool or platform.',
    },
    roadmaps: {
      icon: Info,
      color: '#7C3AED',
      bg: '#F5F3FF',
      title: 'Roadmaps Are General Guides — Not Guaranteed Paths',
      text: 'Career roadmaps are based on publicly available hiring trends and community feedback. Timelines and salary ranges are averages — individual results depend on effort, background, and market conditions. The job market changes frequently.',
    },
    news: {
      icon: Info,
      color: '#0891B2',
      bg: '#ECFEFF',
      title: 'AI-Generated News — For Informational Purposes Only',
      text: 'News and market insights are generated by AI based on general knowledge of the Indian job market. They are not sourced from real-time news feeds. Treat as general guidance, not verified reporting.',
    },
    general: {
      icon: Info,
      color: 'var(--ink-soft)',
      bg: 'var(--bg-panel)',
      title: 'Student Project — Use Responsibly',
      text: 'JobReady is a student-built AI project for educational and portfolio purposes. All AI-generated content is for guidance only. Always verify important career decisions with qualified professionals.',
    },
  }

  const d = disclaimers[type] || disclaimers.general
  const Icon = d.icon

  return (
    <div className="flex items-start gap-3 p-3.5 rounded-xl mb-5"
      style={{ background: d.bg, border: `1px solid ${d.color}33` }}>
      <Icon size={14} style={{ color: d.color, flexShrink: 0, marginTop: 1 }} />
      <div className="flex-1 min-w-0">
        <p className="text-xs font-semibold mb-0.5" style={{ color: d.color }}>{d.title}</p>
        <p className="text-xs leading-relaxed" style={{ color: 'var(--ink-soft)' }}>{d.text}</p>
      </div>
      {dismissible && (
        <button onClick={() => setDismissed(true)} className="flex-shrink-0 p-0.5 rounded hover:opacity-70">
          <X size={13} style={{ color: 'var(--ink-faint)' }} />
        </button>
      )}
    </div>
  )
}
